# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 664d1d970028d64ac3875115f1438438e9b3c3fe73cdbd65c407bef7631225011fc7700925ae3ddbd23af48e3433181ec86a7f34936ec28b7364d28c9442fd72

test:
  secret_key_base: efb8fa582757eb82e3eadf66fea64c25834996c5517adcaa5789a6d59852d89cbf0d0ee3ea50546d08413a269b79fa48214c5f308c8f87dab31a317a811352f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
